import type { Metadata } from 'next';
import './globals.css';
import '@fontsource/quicksand/500.css';
import '@fontsource/quicksand/600.css';
import '@fontsource/quicksand/700.css';
import { cn } from '@/lib/utils';
import Header from '@/components/app/Header/Header';
import Footer from '@/components/app/Footer/Footer';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <head />
            <body className={cn('bg-background font-[Quicksand] antialiased')}>
                <div className="relative flex min-h-screen flex-col">
                    <Header />
                    <main className="flex-1 w-full overflow-x-hidden">{children}</main>
                    <Footer />
                </div>
            </body>
        </html>
    );
}
